language: go
go:
  - "1.14"
env:
  - "PATH=/home/travis/gopath/bin:$PATH"
script:
  - go test -v -covermode=count -coverprofile=coverage.out ./...
#  - goveralls -coverprofile=coverage.out -service travis-ci -repotoken $COVERALLS_TOKEN
